version: '3.8'
services:
  mongo-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  students:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo-mongodb

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mongo-mongodb

volumes:
  mongo-data:
  